# Generated by Django 4.1 on 2022-08-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
