# Generated by Django 4.1 on 2022-08-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Подразделение(Цех)',
                'verbose_name_plural': 'Подразделения(Цеха)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должностя',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('ochestvo', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.jobtitle')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname'],
            },
        ),
    ]
