# Generated by Django 4.1 on 2022-08-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Подразделение (Цех)', 'verbose_name_plural': 'Подразделения (Цеха)'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['last_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='ochestvo',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='surname',
            new_name='middle_name',
        ),
    ]
