# Generated by Django 4.1 on 2022-08-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_department_options_alter_jobtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.department', verbose_name='Подразделение (Цех)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.jobtitle', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Очество'),
        ),
    ]
